#!/bin/bash
#SBATCH -N 1
#SBATCH -c 4
#SBATCH -t 2:00:00

set -x

cd /home/users/liujx/research/icshm/ic-shm2021-p1/scripts
source /home/users/liujx/.bashrc
conda activate open-mmlab
DATA_ROOT=/home/groups/noh/icshm_data/data_proj1/Tokaido_dataset
python ../modules/data_prep.py --input $DATA_ROOT/img_syn_raw/train --output $DATA_ROOT/img_small/train --option resize --width 640 --height 360 --nearest False
